# Generated by Django 5.0.6 on 2024-05-15 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/slider_images/')),
                ('discount_deal', models.CharField(max_length=100)),
            ],
        ),
    ]
