# Generated by Django 5.0.6 on 2024-06-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='delevary_charge',
        ),
    ]
