# Generated by Django 5.0.6 on 2024-05-16 01:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/slider_images/')),
                ('discount_deal', models.CharField(blank=True, choices=[('HOT DEALS', 'HOT DEALS'), ('NEW ARRAIVELS', 'NEW ARRAIVELS')], max_length=30, null=True)),
                ('sale', models.IntegerField(blank=True, default=0, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
