# Generated by Django 5.0.6 on 2024-06-06 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_featured_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received', models.DateField()),
                ('order_processed', models.DateField()),
                ('manufacturing_in_progress', models.DateField()),
                ('order_dispatched', models.DateField()),
                ('order_delivered', models.DateField()),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='app.checkout')),
            ],
        ),
    ]
