# Generated by Django 5.0.6 on 2024-06-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_delevary_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delevary_charge',
        ),
    ]
