# Generated by Django 5.0.6 on 2024-06-06 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_preorder_user_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.main_category'),
        ),
    ]
