# Generated by Django 5.0.6 on 2024-05-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_slider_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='discount_deal',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sale',
        ),
    ]
